multiple_government_mode: false
multiple_government_base_url: nationbuilder.com
api_exclude_fields: [:ip_address, :sphinx_index, :user_agent, :referrer, :google_token, :google_crawled_at, :activation_code, :salt, :email, :first_name, :last_name, :crypted_password, :is_tagger, :partner_id, :ip_address, :user_agent, :remember_token, :remember_token_expires_at, :referrer, :zip, :birth_date, :city, :state, :is_comments_subscribed, :is_finished_subscribed, :is_followers_subscribed, :is_mergeable, :is_messages_subscribed, :is_newsletter_subscribed, :is_point_changes_subscribed, :is_votes_subscribed, :is_subscribed, :contacts_count, :contacts_invited_count, :contacts_members_count, :contacts_not_invited_count, :code, :rss_code, :address]

facebook_template_ids:
    endorsement_new: 120793035093
    opposition_new: 120794485093
    bulletin_new_priority: 120820050093
    bulletin_new_no_priority: 120821135093
    point_new_down: 120918565093
    point_new_up: 120917705093
    document_new_down: 131039485093
    document_new_up: 131040750093